<?php
/* @var $this Zend_View */
//http://getbootstrap.com/examples/navbar-fixed-top/

$this->headLink()
    ->prependStylesheet("//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css")
    ->prependStylesheet("//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css")
    ->prependStylesheet("//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css");
$this->headMeta()
    ->prependName("viewport", "width=device-width, initial-scale=1")
    ->prependHttpEquiv("X-UA-Compatible", "IE=edge");
$this->headScript()
    ->prependFile("//oss.maxcdn.com/respond/1.4.2/respond.min.js",
        'text/javascript', ['conditional' => 'lt IE 9'])
    ->prependFile("https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js",
        'text/javascript', ['conditional' => 'lt IE 9'])
    ->prependFile($this->baseUrl("/assets/js/ie-emulation-modes-warning.js"),
        'text/javascript')
    ->prependFile($this->baseUrl("/assets/js/ie8-responsive-file-warning.js"),
        'text/javascript', ['conditional' => 'lt IE 9']);
$this->headLink()
    ->headLink([
        'type' => 'image/x-icon',
        'rel' => 'icon',
        'href' => $this->baseUrl("/favicon.ico")
        ], Zend_View_Helper_Placeholder_Container_Abstract::PREPEND)
    ->headLink([
        'type' => 'image/x-icon',
        'rel' => 'shortcut icon',
        'href' => $this->baseUrl("/favicon.ico")
        ], Zend_View_Helper_Placeholder_Container_Abstract::PREPEND);

$this->jQuery()->addJavascriptFile("//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js");

$this->headStyle("body {
  padding-top: 70px;
}", Zend_View_Helper_Placeholder_Container_Abstract::PREPEND);

echo $this->docType(), PHP_EOL;
?><html lang="en">
    <head>
        <?php
        echo $this->headMeta(), PHP_EOL;
        echo $this->headTitle(), PHP_EOL;
        echo $this->headLink(), PHP_EOL;
        echo $this->jQuery()->setRenderMode(ZendX_JQuery::RENDER_STYLESHEETS), PHP_EOL;
        echo $this->headStyle(), PHP_EOL;
        echo $this->headScript(), PHP_EOL;
        ?>
    </head>
    <body>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php
                    echo $this->url([], 'default', true);
                    ?>"><?php echo $this->translate('Profile Manager'); ?></a>
                </div><!-- /.navbar-header -->
                <div id="navbar" class="navbar-collapse collapse">
                    <?php
                    echo $this->navigation()->menu()
                        ->setUlClass("nav navbar-nav")
                        ->setActiveClass("active")
                        ->setMinDepth(1)
                        ->setMaxDepth(1);
                    ?>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-globe fa-3"></i>
                                <?php echo $this->translate('Language')?>                                
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->url(array('lang'=>'vi_VN')); ?>"><?php echo $this->translate("Vietnamese")?></a></li>
                                <li><a href="<?php  echo $this->url(array('lang'=>'en_US')); ?>"><?php echo $this->translate("English");?></a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /#navbar -->
            </div><!-- /.container -->
        </nav>

        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <?php
                    echo $this->navigation()->breadcrumbs()
                        ->setLinkLast(false)
                        ->setPartial(['partial/breadcrumbs.phtml', 'default']);
                    ?>

                    <?php
                    echo $this->layout()->content, PHP_EOL;
                    ?>
                </div>
            </div> <!-- /.row -->
        </div> <!-- /.container -->

        <?php
        echo $this->jQuery()->setRenderMode(
            ZendX_JQuery::RENDER_LIBRARY |
            ZendX_JQuery::RENDER_SOURCES |
            ZendX_JQuery::RENDER_JAVASCRIPT |
            ZendX_JQuery::RENDER_JQUERY_ON_LOAD), PHP_EOL;
        echo $this->inlineScript(), PHP_EOL;
        ?>
    </body>
</html>