<?php
/* @var $this Zend_View */
/* @var $profile Application_Model_ProfileInterface */

if ($this->profileNotFound) {
    echo $this->translate('Profile not found');
    return;
}

$profile = $this->profile;
$deleteProfileUrl = $this->url(['action'=>'delete','controller'=>'profile','module'=>'default'], 'default', true);
?>
<p>
    <?php
    echo $this->translate("Are you sure that you want to delete"), " account name '{$profile->getFullname()}'";
    ?>
</p>
<?php
echo $this->form('delete-profile', ['method'=>'post','action'=> $deleteProfileUrl, "class"=>"form-inline"]);
echo $this->formHidden('id',$profile->getId());
echo $this->formSubmit('del', "Yes",['id'=>'Yes','class'=>"btn btn-danger"]), PHP_EOL;
echo $this->formSubmit('del', "No",['id'=>'No','class'=>"btn btn-default"]);
echo "</form>";
