<?php
/* @var $this Zend_View */
$this->headTitle($this->translate('Profile list'));
$profileCollection = $this->profiles; /* @var $profileCollection Application_Model_ProfileCollectionInterface */

if (0 == $profileCollection->count()):
    echo $this->translate('Empty profile list');
    return;
endif; //if (0==$profileCollection->count())
?>

<table id="table-list-profile">
    <thead id="table-list-profile-head">
        <tr>
            <th>
                <?php echo $this->translate('id'); ?>
            </th>
            <th>
                <?php echo $this->translate('fullname'); ?>
            </th>
            <th>
                <?php echo $this->translate('age'); ?>
            </th>
            <th>
                <?php echo $this->translate('email'); ?>
            </th>
        </tr>
    </thead>

    <tbody id="table-list-profile-body">
        <?php
        foreach ($profileCollection as $profile):
            /* @var $profile Application_Model_ProfileInterface */
            $id       = $this->escape($profile->getId());
            $fullname = $this->escape($profile->getFullname());
            $age      = $this->escape($profile->getAge());
            $email    = $this->escape($profile->getEmail());
            ?>
            <tr>
                <td><?php echo $id; ?></td>
                <td><?php echo $fullname; ?></td>
                <td><?php echo $age; ?></td>
                <td><?php echo $email; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
echo $this->paginationControl(
    $profileCollection, 'Sliding', 'partial/search-pagination.phtml'
);

