<?php
$this->headTitle($this->translate('Profile list'));
?>
<?php if (0 == $this->profiles->count()): ?>
<?php echo $this->translate('Empty profile list');?>
<?php else: ?>
<table id="table-list-profile">
    <thead id="table-list-profile-head">
        <tr>
            <th>
                <?php echo $this->translate('id');?>
            </th>
            <th>
                <?php echo $this->translate('fullname');?>
            </th>
            <th>
                <?php echo $this->translate('age');?>
            </th>
            <th>
                <?php echo $this->translate('email');?>
            </th>
        </tr>
    </thead>

    <tbody id="table-list-profile-body">
    <?php foreach ($this->profiles as $profile /* @var $profile Application_Model_ProfileInterface */): ?>
        <?php
            $id = $this->escape($profile->getId());
            $fullname = $this->escape($profile->getFullname());
            $age = $this->escape($profile->getAge());
            $email = $this->escape($profile->getEmail());
        ?>
        <tr>
            <td><?php echo $id;?></td>
            <td><?php echo $fullname;?></td>
            <td><?php echo $age;?></td>
            <td><?php echo $email;?></td>
        </tr>
    <?php endforeach;?>
    </tbody>

    <tfoot>
        <tr>
            <td colspan="4">&nbsp</td>
        </tr>
    </tfoot>
</table>
<?php endif; //if (0==$this->profiles->count())?>
