<?php
if (!$this->pageCount) {
    return;
}
?>
<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->
<?php
$previous = $this->translate('Previous');
$next     = $this->translate('Next');
?>
<nav class="paginationControl">
    <ul class="pagination">
        <?php if (isset($this->previous)): ?>
            <li>
                <a class="prev" href="<?php echo $this->url(array('page' => $this->previous)); ?>" aria-label="<?php echo $previous ?>">
                    <span aria-hidden="true">&laquo; <?php echo $previous ?></span>
                </a>
            </li>
        <?php else: ?>
            <li class="disabled"><a class="prev" href="#" aria-label="Previous"><span aria-hidden="true">&laquo; <?php echo $previous ?></span></a></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li>
                    <a class="number" href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
                </li>
            <?php else: ?>
                <li class="active">
                    <a class="number" href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?>  <span class="sr-only">(current)</span></a></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
            <li>
                <a class="next" href="<?php echo $this->url(array('page' => $this->next)); ?>" aria-label="<?php echo $next ?>">
                    <span aria-hidden="true"><?php echo $next; ?> &raquo;</span>
                </a>
            </li>
        <?php else: ?>
            <li class="disabled"><a href="#" class="next" aria-label="<?php echo $next; ?>"><span aria-hidden="true"><?php echo $next; ?>  &raquo;</span></a></li>
        <?php endif; ?>
    </ul>
</nav>
